import org.apache.hadoop.security.protocolPB.RefreshUserMappingsProtocolClientSideTranslatorPB;
public class FunctionUse8476 {
public void funcUse() {
RefreshUserMappingsProtocolClientSideTranslatorPB refreshusermappingsprotocolclientsidetranslatorpb = new RefreshUserMappingsProtocolClientSideTranslatorPB();
refreshusermappingsprotocolclientsidetranslatorpb.refreshUserToGroupsMappings();
}
}