import org.apache.hadoop.ipc.proto.GenericRefreshProtocolProtos.GenericRefreshResponseCollectionProtoOrBuilder;
public class FunctionUse15478 {
public void funcUse() {
GenericRefreshResponseCollectionProtoOrBuilder genericrefreshresponsecollectionprotoorbuilder = new GenericRefreshResponseCollectionProtoOrBuilder();
genericrefreshresponsecollectionprotoorbuilder.getResponsesList();
}
}