import org.apache.hadoop.security.proto.RefreshAuthorizationPolicyProtocolProtos.RefreshAuthorizationPolicyProtocolService;
public class FunctionUse9670 {
public void funcUse() {
RefreshAuthorizationPolicyProtocolService refreshauthorizationpolicyprotocolservice = new RefreshAuthorizationPolicyProtocolService();
refreshauthorizationpolicyprotocolservice.getDescriptorForType();
}
}